interface Category {
  label: string;
  id: string;
}

export const categories: Category[] = [
  {
    label: 'Getting Started',
    id: 'gettingStarted',
  },
  {
    label: 'Layout',
    id: 'layout',
  },
  {
    label: 'Forms',
    id: 'forms',
  },
  {
    label: 'Components',
    id: 'components',
  },
  {
    label: 'Typography',
    id: 'typography',
  },
  {
    label: 'Buttons',
    id: 'buttons',
  },
  {
    label: 'Feedback and Overlays',
    id: 'feedbackAndOverlays',
  },
  {
    label: 'Advanced UI',
    id: 'advancedUI',
  },
  {
    label: 'Interactive Features',
    id: 'interactiveFeatures',
  },
  {
    label: 'States and Management',
    id: 'statesAndManagement',
  },
  {
    label: 'Guides and Tools',
    id: 'guidesAndTools',
  },
  {
    label: 'Other',
    id: 'other',
  },
];

// export const allComponents = [
//   {
//     id: generateId(),
//     label: "Home",
//     path: "/",
//     icons: home,
//     desc: "The main landing page of the application, typically providing an overview or entry point to other sections.",
//   },
//   {
//     id: generateId(),
//     label: "Components Overview",
//     path: "/componentsOverview",
//     icons: overview,
//     desc: "A page showcasing all available components in the design system or UI library.",
//   },
//   {
//     id: generateId(),
//     label: "Get Started",
//     path: "/getStarted",
//     icons: getStarted,
//     subMenu: [{ id: 1, label: "Build Tools", path: "/getStarted/buildTools" }],
//     desc: "An introductory guide for developers to begin using the component library or framework.",
//   },
//   {
//     id: generateId(),
//     label: "Typography",
//     path: "/typography",
//     icons: typo,
//     desc: "Documentation and examples of text styles, fonts, and formatting options available in the design system.",
//   },
//   {
//     id: generateId(),
//     label: "Button",
//     path: "/button",
//     icons: button,
//     desc: "Interactive elements used to trigger actions or events in the user interface.",
//   },
//   {
//     id: generateId(),
//     label: "Link Button",
//     path: "/linkButton",
//     icons: linkButton,
//     desc: "A hybrid component combining the functionality of a button with the navigation properties of a link.",
//   },
//   {
//     id: generateId(),
//     label: "Badge",
//     path: "/badge",
//     icons: badge,
//     desc: "Small visual indicators used to highlight information or notify users of a status or count.",
//   },
//   {
//     id: generateId(),
//     label: "Tag",
//     path: "/tag",
//     icons: tags,
//     desc: "Label-like components used for categorization, filtering, or displaying metadata.",
//   },
//   {
//     id: generateId(),
//     label: "Alert",
//     path: "/alert",
//     icons: alert,
//     desc: "Informational messages to notify users of important information or changes in the application state.",
//   },
//   {
//     id: generateId(),
//     label: "Avatar",
//     path: "/avatar",
//     icons: avatar,
//     desc: "Graphical representations of users, typically displayed as profile pictures or icons.",
//   },
//   {
//     id: generateId(),
//     label: "Banner",
//     path: "/banner",
//     icons: banner,
//     desc: "Prominent message displays, often used for announcements or important site-wide notifications.",
//   },
//   {
//     id: generateId(),
//     label: "Breadcrum",
//     path: "/breadCrum",
//     icons: breadcrum,
//     desc: "Navigation aids that show the user's current location in a hierarchical structure of the website.",
//   },
//   {
//     id: generateId(),
//     label: "Fieldset",
//     path: "/fieldset",
//     icons: fieldset,
//     desc: "Containers used to group related form elements and provide a visual boundary and optional label.",
//   },
//   {
//     id: generateId(),
//     label: "Figure",
//     path: "/figure",
//     icons: figure,
//     desc: "Container for images, diagrams, or illustrations, often including a caption or description.",
//   },
//   {
//     id: generateId(),
//     label: "FullScreen Toggle",
//     path: "/fullScreenToggle",
//     icons: fullscreen,
//     desc: "A control to switch between normal and full-screen viewing modes for content or applications.",
//   },
//   {
//     id: generateId(),
//     label: "Grid Background",
//     path: "/gridBackground",
//     icons: grid,
//     desc: "Visual guides or patterns used to align and organize content in a grid-based layout system.",
//   },
//   {
//     id: generateId(),
//     label: "Lists",
//     path: "/lists",
//     icons: list,
//     desc: "Components for displaying collections of items in various formats, such as bulleted, numbered, or custom-styled lists.",
//   },
//   {
//     id: generateId(),
//     label: "Model",
//     path: "/model",
//     icons: modal,
//     desc: "Overlay windows that appear on top of the main content, often requiring user interaction before returning to the main view.",
//   },
//   {
//     id: generateId(),
//     label: "Spinner",
//     path: "/spinner",
//     icons: spinner,
//     desc: "Animated loading indicators to show that content is being processed or loaded.",
//   },
//   {
//     id: generateId(),
//     label: "Table",
//     path: "/table",
//     icons: table,
//     desc: "Components for displaying data in rows and columns, often with sorting, filtering, and pagination capabilities.",
//   },
//   {
//     id: generateId(),
//     label: "Text Highlighter",
//     path: "/textHighlighter",
//     icons: textHighlight,
//     desc: "A utility for emphasizing specific portions of text, often used for search results or important information.",
//   },
//   {
//     id: generateId(),
//     label: "Hooks",
//     path: "/hooks",
//     icons: hooks,
//     desc: "Reusable functions that allow functional components to use state and other React features without writing a class.",
//   },
//   {
//     id: generateId(),
//     label: "Icons",
//     path: "/icons",
//     icons: icons,
//     desc: "A library of graphical symbols used to represent actions, objects, or concepts throughout the interface.",
//   },
//   {
//     id: generateId(),
//     label: "Box",
//     path: "/box",
//     icons: box,
//     desc: "A fundamental layout component used for creating containers with customizable padding, margins, and borders.",
//   },
//   {
//     id: generateId(),
//     label: "Cards",
//     path: "/cards",
//     icons: card,
//     desc: "Containers for displaying content in a visually appealing and organized manner, often used in grid layouts.",
//   },
//   {
//     id: generateId(),
//     label: "CloseButton",
//     path: "/closeButton",
//     icons: closeButton,
//     desc: "A standardized button for closing modal windows, panels, or dismissing notifications.",
//   },
//   {
//     id: generateId(),
//     label: "ContentScrollable",
//     path: "/contentScrollable",
//     icons: contentScrolling,
//     desc: "A component that enables smooth scrolling of content within a fixed container or viewport.",
//   },
//   {
//     id: generateId(),
//     label: "Drawer",
//     path: "/drawer",
//     icons: drawer,
//     desc: "A panel that slides in from the edge of the screen, typically used for navigation or additional content.",
//   },
//   {
//     id: generateId(),
//     label: "Dropdown",
//     path: "/dropdown",
//     icons: dropdown,
//     desc: "A UI element that allows users to select one option from a list of choices that appears when activated.",
//   },
//   {
//     id: generateId(),
//     label: "Forms",
//     path: "/forms",
//     icons: forms,
//     desc: "Components and utilities for creating and managing user input fields and form submissions.",
//   },
//   {
//     id: generateId(),
//     label: "JsonViewer",
//     path: "/jsonViewer",
//     icons: json,
//     desc: "A tool for displaying and navigating JSON data in a structured, human-readable format.",
//   },
//   {
//     id: generateId(),
//     label: "NonIdealState",
//     path: "/nonIdealState",
//     icons: nonIdealState,
//     desc: "Components for displaying empty states, errors, or other scenarios where the ideal content is not available.",
//   },
//   {
//     id: generateId(),
//     label: "Popover",
//     path: "/popover",
//     icons: hooks,
//     desc: "A floating container that appears next to a trigger element, often used for tooltips or contextual information.",
//   },
//   {
//     id: generateId(),
//     label: "Ripple",
//     path: "/ripple",
//     icons: ripple,
//     desc: "A visual effect that creates an expanding circle animation when an element is clicked or touched.",
//   },
//   {
//     id: generateId(),
//     label: "SectionHeader",
//     path: "/sectionHeader",
//     icons: section,
//     desc: "A component for creating consistent headings or titles for different sections of a page or application.",
//   },
//   {
//     id: generateId(),
//     label: "Splitter",
//     path: "/splitter",
//     icons: splitter,
//     desc: "A component that allows users to resize adjacent panes or sections by dragging a divider.",
//   },
//   {
//     id: generateId(),
//     label: "Toast",
//     path: "/toast",
//     icons: toast,
//     desc: "Brief, non-intrusive notifications that appear temporarily to provide feedback or information to the user.",
//   },
//   {
//     id: generateId(),
//     label: "Accordion",
//     path: "/accordion",
//     icons: toast,
//     desc: "A vertically stacked list of headers that can be clicked to reveal or hide associated content sections.",
//   },
//   {
//     id: generateId(),
//     label: "LinkBar",
//     path: "/linkBar",
//     icons: toast,
//     desc: "A horizontal navigation component containing a group of related links or actions.",
//   },
//   {
//     id: generateId(),
//     label: "Stack",
//     path: "/stack",
//     icons: toast,
//     desc: "A layout component for vertically or horizontally stacking child elements with consistent spacing.",
//   },
//   {
//     id: generateId(),
//     label: "State Managment",
//     path: "/stateManagment",
//     icons: toast,
//     desc: "Tools and patterns for managing and updating application state across components and pages.",
//   },
//   {
//     id: generateId(),
//     label: "Guides",
//     path: "/guides",
//     icons: toast,
//     desc: "Documentation and tutorials providing detailed instructions on using various aspects of the component library or framework.",
//   },
//   {
//     id: generateId(),
//     label: "Grid System",
//     path: "/gridSystem",
//     icons: toast,
//     desc: "A layout framework for creating responsive, aligned designs using a system of rows and columns.",
//   },
//   {
//     id: generateId(),
//     label: "Playground",
//     path: "/playground",
//     icons: toast,
//     desc: "An interactive environment for experimenting with and testing components in real-time.",
//   },
//   {
//     id: generateId(),
//     label: "Link",
//     path: "/link",
//     icons: drawer,
//     desc: "A component for creating hyperlinks to navigate between pages or external resources.",
//   },
//   {
//     id: generateId(),
//     label: "Tabs",
//     path: "/tabs",
//     icons: drawer,
//     desc: "A navigation component that organizes content into separate views, allowing users to switch between them.",
//   },
// ];
